yaml
---
- hosts: all
  become: true
  tasks:
    - name: Set root password
      user:
        name: root
        password: "{{ '1q2w3e4R' | password_hash('sha512') }}"

    - name: Make sure root has .ssh directory
      file:
        path: /root/.ssh
        state: directory
        mode: '0700'

    - name: Copy SSH key to root
      copy:
        src: /home/vagrant/.ssh/id_rsa
        dest: /root/.ssh/id_rsa
        owner: root
        group: root
        mode: '0600'

    - name: Ensure SSH key ownership and permissions are correct
      command: chown root:root /root/.ssh/id_rsa

    - name: Enable root login over SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin yes'
        state: present

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted
